### PR TITLE
Add support for Ruby Sass and Compass

### PR DESCRIPTION
**Pull request by vwochnik**
I have created a `gemspec` and a script to add the main main directory to Compass or Sass.

Please, as soon as you merge this, build the gem usiing `gem build sass-burger.gemspec` and then publish using `gem push sass-burger-1.3.0.gem`

For the publishing, you need an account on rubygems.org. If you are not familiar with publishing gems, read [this](http://guides.rubygems.org/publishing/)

### CODE REVIEW

**Comment by jorenvanhee** [comment]
Thanks, I'll take a look at this. Haven't used Compass in a while.

**Comment by vwochnik** [comment]
No, this not exclusively for `compass`. This is for either `compass` OR `sass` if `compass` isn't installed.

**Comment by vwochnik** [comment]
Have you taken a look? As of now, I'm using `sass-burger` by manually copying and including the file.

**Comment by jorenvanhee** [comment]
Done :) Thanks for your contribution!

**Pull request merged**
