### PR TITLE
Added user select:none

### PR DESCRIPTION
**Pull request by urre**
Added user select none so icon don't get selected

### CODE REVIEW

**Comment by jorenvanhee** [comment]
I don't know if this is useful. There isn't really anything that can be copied into the clipboard.

**Comment by urre** [comment]
Not copied into clipboard, but you can accidentally select the icon with the mouse.

Ex. https://dl.dropboxusercontent.com/u/1162759/dump_2015-05-06_09-52-23.png

Really minor thing :)

**Comment by PalleZingmark** [comment]
+1 on this. Minor thing, but really annoying.

**Comment by jorenvanhee** [comment]
Merged! Thanks @urre

**Pull request merged**
